### ISSUE TITLE
Not able to run project 

### ISSUE THREAD

**Issue by yagnikpatel1511** [KevCui/perplexity-cli#1]
I am not able to run the project in my PC so could you please guide me to run project
Please see below error which i am facing 

![image](https://github.com/KevCui/perplexity-cli/assets/58947754/b4fc7b02-e20a-4a47-97d2-63230d608a33)

Thanks

**Comment by KevCui** [comment]
Hey @yagnikpatel1511, run script with nodejs should work on Windows. Please refer to https://stackoverflow.com/questions/70045198/windows-script-host-error-invalid-character-code800a03f6-source-microsoft for more details.
